language: python
sudo: false
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test python=$TRAVIS_PYTHON_VERSION cvxopt matplotlib scipy numpy cython
  - source activate test
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.5" ]]; then
      conda install shapely;
    fi
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      conda install -c auto python-gdsii;
    fi
  - pip install -e .
script:
  - python setup.py test
notifications:
  email: false
